# NOTE: commented out Glacial Cloak and Ramaladni's Icy Grasp as not available yet
# 2d list that stores item values
# first dimension is item type (e.g. back, trinkets)
# second dimension is various items
items = [
    [{
        'name': 'Halo of Transcendence (ZG)',
        'stamina': 17 + 10,
        'intellect': 27,
        'sprit': 22,
        'mp5': 4,
        'healing': 48 + 24,
        'frost_resistance': 10,
        'type': 'head',
    },
    {
        'name': 'Halo of Transcendence (Ice Guard)',
        'stamina': 17,
        'intellect': 27,
        'sprit': 22,
        'frost_resistance': 10 + 10,
        'healing': 48,
        'type': 'head',
    }    
    ],
    [{
        'name': 'Antenna of Invigoration',
        'intellect': 4,
        'mp5': 3,
        'healing': 13,
        'type': 'wand',
    },
    {
        'name': 'Lunar Wand',
        'healing': 20,
        'type': 'wand',
    },
    {
        'name': 'Dragon Wand',
        'healing': 18,
        'type': 'wand',
    },
    {
        'name': 'Banshee Finger',
        'frost_resistance': 10,
        'type': 'wand',
    }    
    ],
    [
    {
        'name': "Sartura's Might",
        'stamina': 6,
        'intellect': 6,
        'healing': 51,
        'type': 'offhand',
    },
    {
        'name': 'Lei of the Lifegiver',
        'mp5': 3,
        'healing': 53,
        'type': 'offhand',
    },
    {
        'name': 'Magebane Scion',
        'frost_resistance': 10,
        'type': 'offhand',
    },  
    ],
    [
     {
        'name': "Ramaladni's Icy Grasp",
        'stamina': 20,
        'frost_resistance': 25,
        'type': 'ring',
     },
     {
        'name': "Band of Icy Depths",
        'stamina': 19,
        'frost_resistance': 20,
        'type': 'ring',
     },
     {
        'name': 'Green FR Ring',
        'frost_resistance': 21,
        'type': 'ring',
    },
    {
        'name': 'Green FR Ring Duplicate',
        'frost_resistance': 21,
        'type': 'ring',
    },
    {
        'name': 'Ring of the Martyr',
        'stamina': 10,
        'mp5': 5,
        'healing': 51,
        'type': 'ring',
    },
    {
        'name': 'Pure Elementium Band',
        'stamina': 9,
        'intellect': 10,
        'spirit': 10,
        'healing': 53,
        'type': 'ring',
    },
    {
        'name': 'Cauterizing Band',
        'stamina': 9,
        'intellect': 12,
        'healing': 46,
        'type': 'ring',
    },
    ],
    [{
        'name': 'Gyrofreeze Ice Reflector',
        'frost_resistance': 15,
        'type': 'trinket',   
    },
    {
        'name': 'Gyrofreeze Ice Reflector Duplicate',
        'frost_resistance': 15,
        'type': 'trinket',   
    },
    {
        'name': 'Rejuvenating Gem',
        'mp5': 9,
        'healing': 66,
        'type': 'trinket',   
    },     
    {
        'name': 'Blue Dragon',
        'mp5': 25,
        'type': 'trinket',   
    },
    {
        'name': 'Shard of the Scale',
        'mp5': 16,
        'type': 'trinket',   
    },
    ],
    [{
        'name': "Tempestria's Frozen Necklace",
        'stamina': 8,
        'intellect': 5,
        'frost_resistance': 15,
        'type': 'neck',   
    },
    {
        'name': "Green FR Neck",
        'frost_resistance': 14,
        'type': 'neck',
    },
    {
        'name': 'Amulet of the Fallen God',
        'stamina': 11,
        'mp5': 6,
        'healing': 57,
        'type': 'neck',
    },
    {
        'name': "Jin'do's Evil Eye",
        'stamina': 5,
        'intellect': 11,
        'sprit': 6,
        'healing': 44,
        'type': 'neck',
    },
    {
        'name': "Amulet of the Shifting Sands",
        'mp5': 6,
        'healing': 46,
        'type': 'neck',
    },
    ],
    [{
        'name': 'Leggings of Transcendence (ZG)',
        'stamina': 16 + 10,
        'intellect': 21,
        'sprit': 21,
        'mp5': 7 + 4,
        'healing': 46 + 24,
        'type': 'legs',
    },
    {
        'name': 'Leggings of Transcendence (Ice Guard)',
        'stamina': 16,
        'intellect': 21,
        'sprit': 21,
        'mp5': 7,
        'frost_resistance': 10,
        'healing': 46,
        'type': 'legs',
    }    
    ],
    [
    {
        'name': 'Glacial Cloak',
        'stamina': 18,
        'frost_resistance': 24,
        'type': 'back',
    },
    {
        'name': 'Green FR Cloak',
        'frost_resistance': 15,
        'type': 'back',
    },
    {
        'name': 'Icy Cloak',
        'spirit': 6,
        'frost_resistance': 11,
        'type': 'back',
    },
    {
        'name': 'Frostweaver Cape',
        'intellect': 12,
        'spirit': 12,
        'frost_resistance': 10,
        'type': 'back',
    },
    {
        'name': 'Sapphiron Drape',
        'intellect': 17,
        'stamina': 10,
        'frost_resistance': 6,
        'healing': 14,
        'type': 'back',
    },
    {
        'name': "Frostwolf Advisor's Cloak",
        'stamina': 11,
        'frost_resistance': 5,
        'healing': 14,
        'type': 'back',
    },
    {
        'name': "Cloak of Clarity",
        'intellect': 12,
        'stamina': 6,
        'spirit': 7,
        'mp5': 8,
        'healing': 40,
        'type': 'back',
    }, 
    {
        'name': 'Hide of the Wild',
        'intellect': 10,
        'stamina': 8,
        'healing': 42,
        'type': 'back',
    },
    ]   
]